# Generated by Django 5.0.2 on 2024-02-27 19:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(error_messages={'unique': 'Email already exists.'}, max_length=254, unique=True)),
                ('name', models.CharField(max_length=240)),
                ('first_name', models.CharField(max_length=80)),
                ('second_name', models.CharField(max_length=80)),
            ],
        ),
    ]
