# Generated by Django 5.0.2 on 2024-04-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_user_delete_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.TextField(default='https://i.postimg.cc/V6zbW55L/blank-profile-picture.png'),
        ),
    ]
