# Generated by Django 5.0.2 on 2024-02-29 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='degree',
            field=models.CharField(default='1', max_length=1),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(default='primary', max_length=80),
        ),
        migrations.AddField(
            model_name='course',
            name='section',
            field=models.CharField(default='A', max_length=80),
        ),
    ]
