# Generated by Django 5.0.2 on 2024-03-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_course_degree_course_level_course_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='course',
            name='level',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=80),
        ),
    ]
