# Generated by Django 5.0.2 on 2024-03-04 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_alter_course_degree_alter_course_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='section',
            field=models.CharField(max_length=1),
        ),
    ]
