# Generated by Django 5.0.2 on 2024-03-04 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calification',
            name='calification',
            field=models.FloatField(default=0),
        ),
    ]
