# Generated by Django 5.0.2 on 2024-04-09 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calification', '0002_alter_calification_calification'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calification',
            old_name='calification',
            new_name='pe',
        ),
        migrations.AddField(
            model_name='calification',
            name='pp',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='calification',
            name='pt',
            field=models.FloatField(default=0),
        ),
    ]
