# Generated by Django 5.0.2 on 2024-02-29 22:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0003_course_degree_course_level_course_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=240)),
                ('first_name', models.CharField(max_length=80)),
                ('second_name', models.CharField(max_length=80)),
                ('average', models.FloatField(default=0)),
                ('califications', models.CharField(default='D', max_length=2)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='course.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
