# Generated by Django 5.0.2 on 2024-03-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='califications',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
