# Generated by Django 5.0.2 on 2024-03-03 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='justification',
            field=models.TextField(blank=True, max_length=240),
        ),
    ]
