# Generated by Django 5.0.2 on 2024-03-03 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendance_missed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='missed',
            field=models.BooleanField(default=False),
        ),
    ]
