# Generated by Django 5.0.2 on 2024-03-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_alter_attendance_missed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attendend',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='late',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='missed',
        ),
        migrations.AddField(
            model_name='attendance',
            name='att',
            field=models.IntegerField(default=0),
        ),
    ]
